### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by floswald** [vasudeva-ram/Julia-SSJ#1]
Hi there, great job I was trying to figure out why your enervated IRF does not look like in their paper. Seems it's not a matter of scaling the yaxis, or at least I couldn't figure out how. I'd like to use this in some work so would convert into a prosper module via pull request if you are interested

**Comment by vasudeva-ram** [comment]
Hi there - pull requests are certainly welcome! And support in making a proper module out of this would be very welcome indeed.

Re: the discrepancies in the IRFs, note that the parameterization in my code here is a little different from the parameterization in the paper. Specifically, in the model presented in the paper (and implemented [here](https://github.com/shade-econ/sequence-jacobian/blob/master/notebooks/krusell_smith.ipynb)), they target a steady state where $r = 0.01$ and $Y_{ss} = 1.0$ and then find a $\beta$ and $Z_{ss}$ such that the capital market clears. In my implementation, I have instead chosen to set $\beta = 0.98$ and $Z_{ss} = 1.0$ and find an $r$ such that markets clear. 

This implies that the final set of steady-state values and parameters are slightly different between here and the paper. This discrepancy could the source of differences in IRF results. As is well known, these models are particularly sensitive to the choice of $\beta$.

Let me know if you have any other questions!

**Comment by floswald** [comment]
I think we can close this now as we agreed to collaborate on this at least in principle ;-)
